version: 40
jobs:
- name: Git Mirror Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/CMNext.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !TagCreateTrigger {}
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
