
#taskfile for building the libraries for admin and clients and creating their packages

version: '3'

tasks:

  build:
    cmds:
    - cmd: npm version {{ .BUILD_VERSION }}
      ignore_error: true #error if run when version is not updated
    - task: ci-build

  ci-build:
    cmds:
    #build admin first
     - cd ../lib/admin && npm install && npm run build
     #install deps and run main build
     - npm install 
     - npm run build
    
  #copy artifacts to temp directory
  postbuild_success:
    cmds:
    - powershell mkdir bin -Force
    #tar the dist output and put it in the output dir
    - cd dist/ && tar -czf '../bin/release.tgz' .

  #clean hook
  clean:
    ignore_error: true
    cmds:
    - for: [ node_modules/, dist/, bin/ ]
      cmd: powershell -Command "Remove-Item -Recurse -Force {{.ITEM}}"